#
# (c) Copyright 2015,2016 Hewlett Packard Enterprise Development LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---
sub_service:
  hosts: NOV-API
  name: nova-api
  service: nova
  monitoring:
    enabled: true
    external_name: compute
    logging_dir: /var/log/nova
  logging_options:
    - files:
      - /var/log/nova/nova-manage.log
      centralized_logging:
        enabled: false
        format: json
      log_rotate:
      - daily
      - compress
      - missingok
      - notifempty
      - copytruncate
      - maxsize 10M
      - rotate 7
      - create 640 root root
    - files:
      - /var/log/nova/nova-api.log
      centralized_logging:
        enabled: false
        format: json
      log_rotate:
      - daily
      - compress
      - missingok
      - notifempty
      - copytruncate
      - maxsize 180M
      - rotate 7
      - create 640 nova adm
    - files:
      - /var/log/nova/nova-api-json.log
      centralized_logging:
        enabled: true
        format: rawjson
      log_rotate:
      - daily
      - compress
      - missingok
      - notifempty
      - copytruncate
      - maxsize 20M
      - rotate 5
      - create 640 nova adm
    - files:
      - /var/log/nova/nova-baremetal-deploy-helper.log
      - /var/log/nova/nova-cert.log
      - /var/log/nova/nova-consoleauth.log
      - /var/log/nova/nova-novncproxy.log
      centralized_logging:
        enabled: false
        format: json
      log_rotate:
      - daily
      - compress
      - missingok
      - notifempty
      - copytruncate
      - maxsize 4M
      - rotate 7
      - create 640 nova adm
    - files:
      - /var/log/nova/nova-baremetal-deploy-helper-json.log
      - /var/log/nova/nova-cert-json.log
      - /var/log/nova/nova-consoleauth-json.log
      - /var/log/nova/nova-novncproxy-json.log
      centralized_logging:
        enabled: true
        format: rawjson
      log_rotate:
      - daily
      - compress
      - missingok
      - notifempty
      - copytruncate
      - maxsize 4M
      - rotate 5
      - create 640 nova adm
    - files:
      - /var/log/nova/nova-conductor.log
      centralized_logging:
        enabled: false
        format: json
      log_rotate:
      - daily
      - compress
      - missingok
      - notifempty
      - copytruncate
      - maxsize 400M
      - rotate 7
      - create 640 nova adm
    - files:
      - /var/log/nova/nova-conductor-json.log
      centralized_logging:
        enabled: true
        format: rawjson
      log_rotate:
      - daily
      - compress
      - missingok
      - notifempty
      - copytruncate
      - maxsize 30M
      - rotate 5
      - create 640 nova adm
    - files:
      - /var/log/nova/nova-scheduler.log
      centralized_logging:
        enabled: false
        format: json
      log_rotate:
      - daily
      - compress
      - missingok
      - notifempty
      - copytruncate
      - maxsize 100M
      - rotate 7
      - create 640 nova adm
    - files:
      - /var/log/nova/nova-scheduler-json.log
      centralized_logging:
        enabled: true
        format: rawjson
      log_rotate:
      - daily
      - compress
      - missingok
      - notifempty
      - copytruncate
      - maxsize 10M
      - rotate 5
      - create 640 nova adm
    - files:
      - nova/nova-audit.log
      centralized_audit_logging:
        enabled: true
        format: rawjson
